import { NextRequest, NextResponse } from 'next/server';
import { promises as fs } from 'fs';
import path from 'path';

const CONFIG_FILE = path.join(process.cwd(), '..', 'backend', 'db-config.json');
const ENV_FILE = path.join(process.cwd(), '..', 'backend', '.env');

interface DbConfig {
  useEnvConfig: boolean;
  provider: 'neon' | 'postgres' | 'mysql' | 'mongodb';
  databaseUrl: string;
  directDatabaseUrl?: string;
  poolMin?: number;
  poolMax?: number;
  connectTimeoutMs?: number;
  updatedAt: string;
}

async function readConfig(): Promise<DbConfig | null> {
  try {
    const content = await fs.readFile(CONFIG_FILE, 'utf-8');
    return JSON.parse(content);
  } catch {
    return null;
  }
}

async function readEnvValues(): Promise<{ provider: string; databaseUrl: string; directDatabaseUrl: string }> {
  const result = { provider: 'neon', databaseUrl: '', directDatabaseUrl: '' };
  try {
    const content = await fs.readFile(ENV_FILE, 'utf-8');
    for (const line of content.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eqIdx = trimmed.indexOf('=');
      if (eqIdx === -1) continue;
      const key = trimmed.slice(0, eqIdx).trim();
      const val = trimmed.slice(eqIdx + 1).trim();
      if (key === 'DB_TYPE') result.provider = val || 'neon';
      else if (key === 'DATABASE_URL') result.databaseUrl = val;
      else if (key === 'DIRECT_DATABASE_URL') result.directDatabaseUrl = val;
    }
  } catch { /* ignore */ }
  return result;
}

export async function GET() {
  const config = await readConfig();
  const envValues = await readEnvValues();
  return NextResponse.json({ data: config, env: envValues });
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json() as Partial<DbConfig> & { useEnvConfig?: boolean };

    // If user wants to use .env, write a minimal config that signals this
    if (body.useEnvConfig === true) {
      const config: DbConfig = {
        useEnvConfig: true,
        provider: 'neon',
        databaseUrl: '',
        updatedAt: new Date().toISOString(),
      };
      await fs.writeFile(CONFIG_FILE, JSON.stringify(config, null, 2), 'utf-8');
      // Remove .env.override so backend falls back to .env
      try { await fs.unlink(path.join(process.cwd(), '..', 'backend', '.env.override')); } catch { /* ok */ }
      return NextResponse.json({ success: true, data: config, message: 'Switched to .env configuration. Restart the backend server to apply.' });
    }

    if (!body.provider || !body.databaseUrl) {
      return NextResponse.json({ error: 'Provider and Database URL required' }, { status: 400 });
    }

    const config: DbConfig = {
      useEnvConfig: false,
      provider: body.provider as DbConfig['provider'],
      databaseUrl: body.databaseUrl,
      directDatabaseUrl: body.directDatabaseUrl || undefined,
      poolMin: body.poolMin || 1,
      poolMax: body.poolMax || 10,
      connectTimeoutMs: body.connectTimeoutMs || 30000,
      updatedAt: new Date().toISOString(),
    };

    await fs.writeFile(CONFIG_FILE, JSON.stringify(config, null, 2), 'utf-8');

    // Also generate/update a .env.override file that backend can source
    const envPath = path.join(process.cwd(), '..', 'backend', '.env.override');
    const envContent = [
      `# Auto-generated by Dev Database Config UI (${new Date().toISOString()})`,
      `DB_TYPE=${config.provider}`,
      `DATABASE_URL=${config.databaseUrl}`,
      config.directDatabaseUrl ? `DIRECT_DATABASE_URL=${config.directDatabaseUrl}` : '',
      `DB_POOL_MIN=${config.poolMin}`,
      `DB_POOL_MAX=${config.poolMax}`,
      `DB_CONNECT_TIMEOUT_MS=${config.connectTimeoutMs}`,
    ].filter(Boolean).join('\n') + '\n';
    await fs.writeFile(envPath, envContent, 'utf-8');

    return NextResponse.json({ success: true, data: config, message: 'Configuration saved. Restart the backend server to apply changes.' });
  } catch (e) {
    return NextResponse.json({ error: (e as Error).message }, { status: 500 });
  }
}
